version: '3'

services:
  site:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./website-docker:/usr/share/nginx/html
      - ./nginx:/etc/nginx/sites-enabled
    container_name: webserver
  
    